
dep.require 'hs.Template'

dep.provide 'hs.t.TermsAndConditions'

class hs.t.TermsAndConditions extends hs.Template

  prependTo: '#main'

  template:-> """
    <div class="flatpage">
      <h1>Terms and Conditions of Use</h1>

      <h3>1.  Acceptance of Terms</h3>
      <p>This document constitutes a legal agreement between you and Hipsell Inc. (“Hipsell”) setting forth the terms and conditions that governs your access to, and use of, the services, websites, applications and intellectual property of Hipsell Inc. made available to you (collectively the “Service”). By accessing and/or using the Service, you acknowledge that you have read, understood and agree to abide by and comply with all the terms, conditions and notices contained in or referenced by these Terms and Conditions of Use and Hipsell’s Privacy Policy annexed hereto (the “Terms and Conditions of Use” or “Agreement”). Hipsell reserves the right, in its discretion, to update or revise these Terms and Conditions of Use and to post such updated or revised Terms and Conditions of Use on its website at www.connectsy.com.  Please check the Terms and Conditions of Use periodically for changes. Your continued use of the Service following the posting of any changes to the Terms and Conditions of Use constitutes acceptance of those changes.</p>
      <p>For purposes of these Terms and Conditions of Use, the term:</p>
      <p>“Content” means and includes, without limitation, text, email or other electronic messages, attachments, videos, audio clips, written comments, information, data, photographs, software, scripts, graphics and interactive features and any similar or related material or content that can be Transmitted utilizing the Service, including User Submissions; </p>
      <p>“Transmit” means and includes post, display, input, submit, disseminate, deliver, upload, communicate, send, download, make available, publicly disclose, transmit or otherwise make accessible, or the intent to do any of the foregoing, to any other person or entity; and</p>
      <p>“User Submissions” means any Content originating from you;</p>
      <p>You may use the Service only if you can form a legally binding contract with Hipsell, and your use of the Service shall constitute your representation and warranty to Hipsell that you have the legal capacity to enter into this Agreement.  This Agreement will not be binding on Hipsell, nor will your access to, or use of, the Service be permitted if such access or use is not in compliance with any applicable local, provincial, state, federal, national, or international law, rule, regulation or policy having the force of law. </p>

      <h3>2.  Third Party Information and Links</h3>
      <p>The Service may contain links to third party websites, services or resources (“Third Party Resources”).  When you access such Third Party Resources you do so at your own risk.  Third party resources are not under the control of Hipsell, and Hipsell is not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such Third Party Resources. Links and information to such Third Party Resources are provided as a convenience to you only and the inclusion in the Service does not imply endorsement by Hipsell of any such Third Party Resources.  Any dealings with third parties (whether or not utilizing a Third Party Resource) initiated, conducted through, or in any way directly or indirectly involving or related to the Service are solely between you and the third party. Hipsell shall not be responsible or liable for any damage or loss caused or alleged to be caused, directly or indirectly, related to arising from or in connection with any such dealings with third parties. Use of any Third Party Resources is subject to the terms of use of such third party.</p>

      <h3>3.  Your Use Obligations</h3>
      <p>Hipsell grants each user of the Service a worldwide, non-exclusive, non-sublicensable and non-transferable license to use the Service to Transmit and receive Content, solely for personal, non-commercial use.</p>
      <p>In consideration of your use of the Service, you agree to provide true, accurate, current and complete information about yourself as required by the registration process and you agree to promptly update that information with any changes. </p>
      <p>You are responsible for all activities undertaken by you using the Service and agree and acknowledge that your use of the Service is at your own risk. You shall not use the Service in a manner or for a purpose contrary to these Terms and Conditions of Use. You are responsible for all activities that occur under your password or account, and you will keep your password(s) confidential. We encourage you to use “strong” passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. Hipsell Inc. will not be liable for any loss or damage arising from your failure to comply with these requirements. You will immediately notify us of any unauthorized use of your password or account or any other breach of security. </p>

      <h3>4.  Prohibited Uses</h3>
      <p>You may not use the Service in any manner which could damage, disable, overburden, or impair the Service or the facilities or equipment of Hipsell or interfere with any other party's use and enjoyment of the Service. You may not attempt to gain unauthorized access to the Service, other accounts, computer systems or networks connected to the Service, through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available to you through Service.</p>
      <p>The Service uses e-mail and/or other message or communication facilities designed to enable you to communicate with others. You agree to use the Service only to Transmit and receive Content that is  proper, not objectionable and not in contravention of these Terms and Conditions of Use. By way of example, and not as a limitation, you agree that when using the Service, you will not:</p>
      <ul>
        <li>infringe any patent, trademark, trade secret, copyright, right of publicity or other right of any other person or entity or violate any law, fiduciary or contractual duty;</li>
        <li>Transmit anything that you know is false, misleading, untruthful or inaccurate; </li>
        <li>Transmit anything that is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another's privacy, tortious, obscene, vulgur, pornographic, offensive, profane, or otherwise inappropriate as determined by Hipsell in its sole discretion;</li>
        <li>Transmit anything that constitutes unauthorized or unsolicited advertising, junk or bulk e-mail ("spamming");</li>
        <li>Transmit anything that involves commercial activities and/or sales such as contests, sweepstakes, barter, advertising, or pyramid schemes;</li>
        <li>Transmit anything that contains software viruses or any other computer codes, files, or programs that are designed or intended to disrupt, damage, limit or interfere with the proper function of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any system, data, password or other information of Hipsell or any third party;</li>
        <li>impersonate any person or entity;</li>
        <li>harvest or otherwise collect information about others, including e-mail addresses; or</li>
        <li>violate any applicable laws or regulations.</li>
      </ul>
      <p>Hipsell has no obligation to monitor the Service. However, Hipsell reserves the right to review any Content and to remove any Content in its sole discretion. Hipsell further reserves the right to terminate or restrict your access to any or all of the Services at any time and from time to time, without notice, for any reason whatsoever or no reason.</p>
      <p>Hipsell reserves the right at all times to disclose any information as Hipsell deems necessary to satisfy any applicable law, regulation, legal process or governmental request.</p>

      <h3>5.  User Submissions</h3>
      <p>Hipsell does not claim ownership of any User Submissions. You hereby irrevocably grant Hipsell a worldwide, non-exclusive, perpetual, royalty-free license (with the right to sublicense) to use, reproduce, adapt, modify, publish, Transmit, perform, display, distribute and make derivative works of any of your User Submissions using any and all media, distribution and Tranmission methods (now known or later developed) and to use your User Submissions in connection with the operation of its business (without attribution). </p>
      <p>Hipsell is under no obligation to use, Transmit or take any other action with respect to your User Submissions and Hipsell may remove any User Submission at any time in its sole discretion. By using the Service, you represent and warrant that you own or otherwise control all of the rights to your User Submissions including, without limitation, all the rights necessary for you to Transmit such User Submissions. Hipsell does not represent or warrant the accuracy, copyright compliance, legality, integrity, quality, or decency of any Content. </p>

      <h3>6.  International Use</h3>
      <p>The Service may be accessed globally. You agree and undertake to access the Service in compliance with all applicable local use controls, laws and regulations. Hipsell makes no representation or warranty and assumes no liability or responsibility to ensure that access and use of the Service is permissible in any jurisdiction.</p>

      <h3>7.  Use of Email services</h3>
      <p>You agree that Hipsell may establish limits concerning use of the Services, including without limitation, the maximum number of days that messages will be retained or available, the maximum number of messages that may be sent from or received by an account, the maximum size of any message that may be sent from or received by an account, the maximum disk space that will be allotted on Hipsell’s servers on your behalf, and the maximum number of times and duration you may access the service in a given period of time.  Hipsell may change the limits or prescribe new limits at any time and from time to time without prior notice.</p>
      <p>You agree that Hipsell has no responsibility or liability for the deletion, corruption or failure to store or Transmit any Content for any reason whatsoever or to maintain the Service. You acknowledge that Hipsell reserves the right to delete accounts without notice to you for any reason. </p>

      <h3>8.  Disclaimer of Warranties</h3>
      <p>ALL MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND OTHER CONTENT CONTAINED IN OR ASSOCIATED WITH THE SERVICE, OR OBTAINED FROM A THIRD PARTY RESOURCE LINKED TO THE SERVICE IS PROVIDED TO YOU ON AN "AS IS", “WHERE IS” AND “AS AVAILABLE” BASIS, WITHOUT WARRANTY OR CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, SECURITY OR ACCURACY. HIPSELL ASSUMES NO RESPONSIBILITY FOR ANY ERRORS, OMISSIONS OR INACCURACIES WHATSOEVER IN THE SERVICE OR RELATING TO THE CONTENT TRANSMITTED CONNECTION WITH THE SERVICE. UNDER NO CIRCUMSTANCES WILL HIPSELL BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY YOUR RELIANCE ON THE CONTENT TRANSMITTED OR THE FAILURE TO TRANSMIT CONTENT THROUGH THE SERVICE. IT IS YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS AND USEFULNESS OF ANY CONTENT.  HIPSELL DOES NOT WARRANT THAT: (A) THE SERVICE WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (C) ANY CONTENT OR SOFTWARE AVAILABLE OR USED IN CONNECTION WITH THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE SERVICE WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE SERVICE IS SOLELY AT YOUR OWN RISK. HIPSELL MAKES NO WARRANTY THAT THE SERVICE WILL BE AVAILABLE, UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE.</p>
      <p>By Submitting your name, contact information, and any personal information in connection with your use of the Service places that information into a public forum and Hipsell will not be liable or responsible for any costs, damages or consequences in connection therewith whatsoever, including as a result of negligence.</p>

      <h3>9.  Limitation of Liability</h3>
      <p>YOU SPECIFICALLY AGREE THAT HIPSELL WILL NOT BE RESPONSIBLE OR LIABILE FOR UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OF CONTENT, ANY CONTENT TRANSMITTED OR NOT TRANSMITTED OR RECEIVED OR NOT RECIEVED. YOU SPECIFICALLY AGREE THAT HIPSELL IS NOT RESPONSIBLE OR LIABLE FOR ANY THREATENING, DEFAMATORY, OBSCENE, OFFENSIVE OR ILLEGAL CONTENT OR CONDUCT OF ANY OTHER PARTY OR ANY INFRINGEMENT OF ANOTHER'S RIGHTS, INCLUDING INTELLECTUAL PROPERTY RIGHTS. YOU SPECIFICALLY AGREE THAT HIPSELL IS NOT RESPONSIBLE FOR ANY CONTENT SENT USING THE SERVICE. </p>
      <p>IN NO EVENT SHALL HIPSELL BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER, WHETHER IN CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE ARISING OUT OF OR IN CONNECTION WITH OR RELATING TO THIS AGREEMENT, WHETHER OR NOT HIPSELL HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </p>
      <p>HIPSELL MAKES NO GUARANTY OF CONFIDENTIALITY OR PRIVACY OF ANY COMMUNICATION OR CONTENT TRANSMITTED UTILIZING THE SERVICE OR ANY THIRD PARTY RESOURCE LINKED TO THE SERVICE. HIPSELL will not be liable for the privacy of email addresses, registration and identification information, communications, confidential or other information comprising any content stored on or transmitted using Hipsell’s equipment, transmitted over networks accessed by the Service, or otherwise connected with your use of the Service. </p>

      <h3>10.  Indemnification</h3>
      <p>You shall defend, indemnify, and hold harmless Hipsell, its affiliates and each of its, and its affiliates shareholders, officers, directors, employees, contractors, suppliers and representatives from all liabilities, claims,  costs and expenses, including reasonable attorneys' fees, that arise from or relate to your use or misuse of, or access to, the Service, Content, your User Submissions, a violation of this Agreement, an infringement by you of any intellectual property or other right of any person or entity or any of the foregoing arising out of or in connection with any third party using your account. Hipsell reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with Hipsell in asserting any available defenses at your expense.</p>

      <h3>11.  Intellectual Property Rights</h3>
      <p>Neither you nor anyone acting on your behalf, including your employees, acquire any intellectual property or other proprietary rights, including patents, designs, trademarks, copyright or trade-secrets, relating to the Service or its content, including without limitation, software and information.</p>

      <h3>12.  Modifications to Services Provided</h3>
      <p>Hipsell reserves the right at any time and from time to time, at its sole discretion, to modify or discontinue, temporarily or permanently, any or all of the Service with or without notice, (including without limitation, the availability of any feature or Content).  You agree that Hipsell shall not be liable to you or to any third party for any modification, suspension or discontinuance of such services.</p>

      <h3>13.  General</h3>
      <p>This agreement is governed by the laws of the Province of Ontario, Canada, without regard to conflict of laws provisions, and you agree to submit to the exclusive jurisdiction of the courts located in the Province of Ontario, Canada. No joint venture, partnership, employment, or agency relationship exists between you and Hipsell as a result of this Agreement or use of the Service. If any part of this Agreement is determined to be invalid or unenforceable pursuant to applicable law in any jurisdiction including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded in such jurisdiction by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect. This Agreement constitutes the entire agreement between you and Hipsell with respect to the subject matter hereof and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between you and Hipsell.  A printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express will of the parties that this agreement and all related documents have been drawn up in English. C'est la volont expresse des parties que la prsente convention ainsi que les documents qui s'y rattachent soient rdigs en anglais.</p>
    </div>
  """
